FROM confluentinc/cp-kafka-connect-base:6.2.1

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.0.2

COPY db2jcc4.jar /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/
